global:
  scrape_interval:     15s
  external_labels:
    monitor: 'tech-showcase-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'entertainment-service'
    scrape_interval: 5s
    metrics_path: /observability/metrics
    static_configs:
      - targets: ['entertainment-service:8080']